version: "3.1"
services:
  db:
    image: mysql:8.0.21
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: overflow
      MYSQL_DATABSE: overflow
      MYSQL_PASSWORD: overflow
    ports:
      - "9906:3306"
    volumes:
      - "./db.sql:/docker-entrypoint-initdb.d/db.sql"
    
  web:
    image: ghcr.io/amt-los-pollos-hermanos/overflow:latest
    ports:
      - "9080:9080"


