version: "3.1"
services:
  db:
    image: mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: overflow
      MYSQL_USER: overflow
      MYSQL_PASSWORD: overflow
    ports:
      - "9906:3306"
    volumes:
      - "./db.sql:/docker-entrypoint-initdb.d/db.sql"
    
  web:
    build: .
    ports:
      - "9080:9080"


