name: Build and publish of the docker image of the project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Maven project to war file

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with maven
        run: mvn clean package

      - uses: actions/upload-artifact@v2
        with:
          name: war
          path: target/overflow-1.0-SNAPSHOT.war

  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy Docker image to the GitHub Docker Registry

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: war
          path: target

      - name: Build Docker Image
        run: |
          echo ${{ secrets.DOCKER_PAT }} | docker login ghcr.io -u balsigergil --password-stdin
          docker build -t ghcr.io/amt-los-pollos-hermanos/overflow:latest .
          docker push ghcr.io/amt-los-pollos-hermanos/overflow:latest