name: Build and publish of the docker image of the project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Maven project to war file

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with maven
        run: mvn clean package

      - uses: actions/upload-artifact@v2
        with:
          name: overflow-1.0-SNAPSHOT
          path: target/overflow-1.0-SNAPSHOT.war

  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy Docker image to the GitHub Docker Registry

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: overflow-1.0-SNAPSHOT
          path: target

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: gil
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/amt-los-pollos-hermanos/overflow:latest
          cache-from: type=ghcr.io,ref=amt-los-pollos-hermanos/overflow:latest
          cache-to: type=inline