name: Test

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test project with JUnit

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Test with maven
        run: mvn -B clean test

  e2e:
    runs-on: ubuntu-latest
    name: End user acceptance testing

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Test with maven
        run: mvn -B clean package

      - name: Start services
        run: docker-compose -f docker-compose.test.yml up -d --build

      - uses: actions/setup-node@v1

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies and run tests
        run: npm install && npm run test
        working-directory: e2e
        env:
          ENDPOINT: 'http://localhost:9080/overflow-1.0-SNAPSHOT'
          HEADLESS: true

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: screenshots
          path: e2e/output/*.png